services:
  ollama:
    build:
      context: ./llm
      dockerfile: Dockerfile
    volumes:
      - ./data/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - 5540:5540
    restart: unless-stopped

volumes:
  ollama: {}
  redis: {}
  open-webui: {}
