version: "3.8"
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    expose:
      - "8080"
    ports:
      - "1234:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
  ollama:
    image: ollama/ollama:0.1.34
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
volumes:
  ollama:
  open-webui:
