version: "3.8"
services:
  ui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    expose:
      - "8080"
    ports:
      - "1234:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data/openwebui:/app/backend/data
  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
